# Generated by Django 2.2.9 on 2020-01-20 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_application_sponsorship'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('student', 'sponsorship')},
        ),
    ]
