# Generated by Django 2.2.9 on 2020-01-21 12:16

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200120_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='birth_certificate',
            field=models.URLField(blank=True, default='https://res.cloudinary.com/dakhp08gq/image/upload/v1579606701/noimage.png', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='city',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='country',
            field=models.CharField(default='test', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='cover_letter',
            field=models.CharField(default='test', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='degree',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='first_name',
            field=models.CharField(default='test', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='last_name',
            field=models.CharField(default='test', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='mobile',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
        migrations.AddField(
            model_name='application',
            name='national_id',
            field=models.URLField(blank=True, default='https://res.cloudinary.com/dakhp08gq/image/upload/v1579606701/noimage.png', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='postal_code',
            field=models.CharField(default='test', max_length=12, verbose_name='ZIP / Postal code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='school_name',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='start',
            field=models.IntegerField(choices=[(2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=2020, verbose_name='year'),
        ),
        migrations.AddField(
            model_name='application',
            name='to',
            field=models.IntegerField(choices=[(2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029)], default=2020, verbose_name='year'),
        ),
    ]
