# Generated by Django 2.2.9 on 2020-01-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200121_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='start',
            field=models.IntegerField(choices=[(2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=2020, verbose_name='start'),
        ),
        migrations.AlterField(
            model_name='application',
            name='to',
            field=models.IntegerField(choices=[(2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029)], default=2020, verbose_name='to'),
        ),
    ]
