# Generated by Django 2.2.9 on 2020-01-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200121_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorship',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
